### ISSUE TITLE
About the format of .csv

### ISSUE THREAD

**Issue by xingyizhou** [jsupancic/deep_hand_pose#1]
hello jsupancic,
  I'm trying to run your code but I meet a problem. In "src/caffe/jvl.cpp" line 471, you seem to load NYU labels from several ".csv" files, but there are no ".csv" files in the original NYU datasets. Could you please tell me the format of ".cvs" files in your program or how to generate these files?

Thanks a lot!
Xingyi Zhou

**Comment by jsupancic** [comment]
Dear Xingyi,

I've uploaded the files here:
https://github.com/jsupancic/deep_hand_pose/commit/f01f999e7f307b15fdbdac4e8f8abe9656292994

They basically contain the NYU dataset's annotations, but converted from .mat to .csv. 

Best,
James
