### ISSUE TITLE
Cannot compile on Ubuntu14.04 + CUDA7.5 + CUDNN V5

### ISSUE THREAD

**Issue by yiminglin-ai** [jsupancic/deep_hand_pose#3]
Hi Jsupancic,

When I run your code on Ubuntu14.04 + CUDA7.5 + CUDNN V5, I encounter errors like: 

> /deep_hand_pose/src/caffe/layers/cudnn_relu_layer.cu(20): error: argument of type "cudnnActivationMode_t" is incompatible with parameter of type "cudnnActivationDescriptor_t"
>           detected during instantiation of "void caffe::CuDNNReLULayer<Dtype>::Forward_gpu(const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &, const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &) [with Dtype=float]" 

I suppose it might be caused by  CUDNN v5, Can I know your environment? Or could you please update for the new version since Caffe officially supports this version.

Thank you very much

yl

**Comment by rivercn** [comment]
I got the same errors ，
how did you solved the problem .
Change the CUDNN v5 versions to v4 is OK？
